FROM --platform=$BUILDPLATFORM golang:1.25.8 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

COPY go.mod go.sum ./

RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o reporter cmd/readiness-condition-reporter/main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/reporter .
USER 65532:65532

ENTRYPOINT ["/reporter"]
