apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    nrr-poc-monitoring: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    nrr-poc-monitoring: "true"
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: node-readiness-controller
        static_configs:
          - targets: ['nrr-metrics-service.nrr-system.svc.cluster.local:8080']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    nrr-poc-monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrr-poc-prometheus
  template:
    metadata:
      labels:
        app: nrr-poc-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.53.2
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.enable-lifecycle
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: cfg
              mountPath: /etc/prometheus
      volumes:
        - name: cfg
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    nrr-poc-monitoring: "true"
spec:
  selector:
    app: nrr-poc-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
